// Manual verification script for conceptExport.ts — generates the REAL PDF,
// Word and Excel files (the same libraries the browser loads on click) and
// checks their contents via a small zip reader for the Word/Excel packages —
// same approach as missionExport.manualtest.ts, adapted to Concept Agent's
// content shape. Run directly:
//
//   node src/lib/the-hangar/conceptExport.manualtest.ts
import { inflateRawSync } from "node:zlib";
import { buildConceptExportModel, exportConcept, type ConceptExportInput } from "./conceptExport.ts";

let passCount = 0;
let failCount = 0;

function check(name: string, actual: unknown, expected: unknown): void {
  const pass = JSON.stringify(actual) === JSON.stringify(expected);
  console.log(`${pass ? "PASS" : "FAIL"}  ${name}`);
  if (!pass) {
    console.log(`      expected: ${JSON.stringify(expected)}`);
    console.log(`      actual:   ${JSON.stringify(actual)}`);
  }
  pass ? passCount++ : failCount++;
}

function readZip(buf: Buffer): Map<string, string> {
  let eocd = -1;
  for (let i = buf.length - 22; i >= 0; i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("not a zip: no end-of-central-directory record");
  const entryCount = buf.readUInt16LE(eocd + 10);
  let p = buf.readUInt32LE(eocd + 16);
  const files = new Map<string, string>();
  for (let n = 0; n < entryCount; n++) {
    if (buf.readUInt32LE(p) !== 0x02014b50) throw new Error("bad central directory entry");
    const method = buf.readUInt16LE(p + 10);
    const compressedSize = buf.readUInt32LE(p + 20);
    const nameLen = buf.readUInt16LE(p + 28);
    const extraLen = buf.readUInt16LE(p + 30);
    const commentLen = buf.readUInt16LE(p + 32);
    const localOffset = buf.readUInt32LE(p + 42);
    const name = buf.toString("utf8", p + 46, p + 46 + nameLen);
    const dataStart = localOffset + 30 + buf.readUInt16LE(localOffset + 26) + buf.readUInt16LE(localOffset + 28);
    const raw = buf.subarray(dataStart, dataStart + compressedSize);
    files.set(name, (method === 8 ? inflateRawSync(raw) : raw).toString("utf8"));
    p += 46 + nameLen + extraLen + commentLen;
  }
  return files;
}
const count = (haystack: string, needle: string): number => haystack.split(needle).length - 1;

const input: ConceptExportInput = {
  conceptCode: "CN-2609221530-XY9",
  generatedAt: "2026-09-22T10:00:00.000Z",
  confidenceScore: 0.8,
  version: 1,
  candidates: [
    { conceptName: "AgriHawk", description: "Fixed-wing crop survey platform", vehicleClass: "Fixed-wing", rationale: "Long endurance for large-acreage coverage" },
    { conceptName: "SprayCopter", description: "Multirotor precision sprayer", vehicleClass: "Multirotor", rationale: "VTOL for tight field access" },
    { conceptName: "HybridScout", description: "VTOL hybrid survey + spray", vehicleClass: "VTOL Hybrid", rationale: "Covers both survey and treatment in one platform" },
  ],
  tradeoffNotes: [
    { conceptName: "AgriHawk", prosCons: ["+ long range", "- needs a runway"], constraintFit: "pass", fitScore: 9, rationale: "Meets range and payload with margin" },
    { conceptName: "SprayCopter", prosCons: ["+ no runway needed", "- shorter range"], constraintFit: "partial", fitScore: 6, rationale: "Range is below target by 15%" },
    { conceptName: "HybridScout", prosCons: ["+ dual mode", "- higher cost"], constraintFit: "fail", fitScore: 3, rationale: "Exceeds budget constraint" },
  ],
  rankedConcepts: [
    { rank: 2, conceptName: "SprayCopter", description: "Multirotor precision sprayer", constraintFit: "partial", fitScore: 6, rationale: "Range is below target by 15%" },
    { rank: 1, conceptName: "AgriHawk", description: "Fixed-wing crop survey platform", constraintFit: "pass", fitScore: 9, rationale: "Meets range and payload with margin" },
    { rank: 3, conceptName: "HybridScout", description: "VTOL hybrid survey + spray", constraintFit: "fail", fitScore: 3, rationale: "Exceeds budget constraint" },
  ],
};

console.log("--- model ---");
const model = buildConceptExportModel(input);
check("footer carries the spec version", model.footer, "Generated by Concept Agent — Bay 02, The Hangar. Version 1.");
check("file name is sanitised and versioned", model.fileBase, "CN-2609221530-XY9-concept-spec-v1");
check("confidence label is a whole-number percent", model.confidenceLabel, "80%");
check("top concept name comes from rank 1, not array order", model.topConceptName, "AgriHawk");
check("ranked concepts are sorted by rank, not input order", model.rankedConcepts.map((r) => r.name), ["AgriHawk", "SprayCopter", "HybridScout"]);
check("fit labels are humanised", model.rankedConcepts.map((r) => r.fitLabel), ["Fits", "Partial fit", "Doesn't fit"]);
check("fit score is formatted as x/10", model.tradeoffNotes[0].fitScore, "9/10");

const noVersion = buildConceptExportModel({ ...input, version: null, generatedAt: null });
check("an unknown version is omitted from the footer/file name", [noVersion.footer, noVersion.fileBase, noVersion.generatedLabel], ["Generated by Concept Agent — Bay 02, The Hangar.", "CN-2609221530-XY9-concept-spec", null]);
check("a hostile concept code can't escape the file name", buildConceptExportModel({ ...input, conceptCode: "../../x y.pdf" }).fileBase.includes("/"), false);

console.log("\n--- generated files ---");
const files: Record<string, Buffer> = {};
for (const format of ["pdf", "docx", "xlsx"] as const) {
  const { blob, fileName } = await exportConcept(format, model);
  files[format] = Buffer.from(await blob.arrayBuffer());
  check(`${format}: file name`, fileName, `CN-2609221530-XY9-concept-spec-v1.${format}`);
}

// PDF
const pdfText = files.pdf.toString("latin1");
check("pdf: starts with the PDF header", pdfText.startsWith("%PDF-"), true);
check("pdf: footer with the version is in the file", pdfText.includes("Version 1."), true);
check("pdf: the top concept's name appears", pdfText.includes("AgriHawk"), true);

// Word
const docx = readZip(files.docx);
const docXml = docx.get("word/document.xml") ?? "";
check("docx: core parts present", ["word/document.xml", "word/footer1.xml", "[Content_Types].xml"].every((n) => docx.has(n)), true);
check("docx: three tables (ranked, candidates, trade-off)", count(docXml, "<w:tbl>"), 3);
check("docx: the rank-1 row is shaded", count(docXml, 'w:fill="FFF0CD"'), 5);
check("docx: ranked order matches the model (sorted), not raw input order", docXml.indexOf(">AgriHawk<") < docXml.indexOf(">SprayCopter<") && docXml.indexOf(">SprayCopter<") < docXml.indexOf(">HybridScout<"), true);
const footXml = docx.get("word/footer1.xml") ?? "";
check("docx: footer has the version and live page-number fields", footXml.includes("Version 1.") && footXml.includes("PAGE") && footXml.includes("NUMPAGES"), true);

// Excel
const xlsx = readZip(files.xlsx);
const wbXml = xlsx.get("xl/workbook.xml") ?? "";
check("xlsx: four sheets, named per the spec", ["Overview", "Ranked Concepts", "Candidates", "Trade-off Notes"].every((n) => wbXml.includes(`name="${n}"`)), true);
check("xlsx: exactly 4 worksheets", [...xlsx.keys()].filter((k) => /^xl\/worksheets\/sheet\d+\.xml$/.test(k)).length, 4);
const strings = xlsx.get("xl/sharedStrings.xml") ?? "";
check("xlsx: pros/cons text is present", strings.includes("long range"), true);
const overview = xlsx.get("xl/worksheets/sheet1.xml") ?? "";
check("xlsx: confidence is stored as a number (0.8), not text", overview.includes("<v>0.8</v>"), true);
check("xlsx: Ranked Concepts sheet has 4 rows (header + 3)", count(xlsx.get("xl/worksheets/sheet2.xml") ?? "", "<row "), 4);
check("xlsx: Candidates sheet has 4 rows (header + 3)", count(xlsx.get("xl/worksheets/sheet3.xml") ?? "", "<row "), 4);
check("xlsx: Trade-off Notes sheet has 4 rows (header + 3)", count(xlsx.get("xl/worksheets/sheet4.xml") ?? "", "<row "), 4);

console.log("\n--- empty spec still exports in every format ---");
const empty = buildConceptExportModel({ ...input, candidates: [], tradeoffNotes: [], rankedConcepts: [] });
for (const format of ["pdf", "docx", "xlsx"] as const) {
  let ok = true;
  let bytes = 0;
  try {
    bytes = (await (await exportConcept(format, empty)).blob.arrayBuffer()).byteLength;
  } catch {
    ok = false;
  }
  check(`${format}: no candidates/ranked/trade-off notes`, ok && bytes > 500, true);
}
const emptyDoc = readZip(Buffer.from(await (await exportConcept("docx", empty)).blob.arrayBuffer())).get("word/document.xml") ?? "";
check(
  "docx (empty): no tables; the empty sections say so",
  count(emptyDoc, "<w:tbl>") === 0 &&
    emptyDoc.includes("No ranked concepts.") &&
    emptyDoc.includes("No candidate concepts.") &&
    emptyDoc.includes("No trade-off notes."),
  true,
);

console.log(`\n${passCount} passed, ${failCount} failed`);
if (failCount > 0) process.exit(1);
