// Concept spec export — PDF, Word (.docx) and Excel (.xlsx) — same approach
// as Mission Agent's missionExport.ts: generated in the browser on demand
// from the spec already on screen (not by the pipeline), so the export can
// never drift from what the dashboard shows, and needs no server-side file
// generation. Shared low-level pieces (pdfSafe, the format metadata, the
// download helper) are imported from missionExport.ts rather than
// duplicated — they're generic, not Mission-specific.
import {
  EXPORT_FORMAT_META,
  downloadBlob,
  pdfSafe,
  type MissionExportFormat,
} from "./missionExport.ts";
export { EXPORT_FORMAT_META, downloadBlob, type MissionExportFormat as ConceptExportFormat };

export interface ConceptExportInput {
  conceptCode: string;
  /** ISO timestamp the spec was generated; null when unknown. */
  generatedAt: string | null;
  confidenceScore: number;
  /** Persisted spec version, when known — appears in the footer and file name. */
  version: number | null;
  candidates: { conceptName: string; description: string; vehicleClass: string; rationale: string }[];
  tradeoffNotes: {
    conceptName: string;
    prosCons: string[];
    constraintFit: "pass" | "partial" | "fail";
    fitScore: number;
    rationale: string;
  }[];
  rankedConcepts: {
    rank: number;
    conceptName: string;
    description: string;
    constraintFit: "pass" | "partial" | "fail";
    fitScore: number;
    rationale: string;
  }[];
}

const FIT_LABEL: Record<string, string> = { pass: "Fits", partial: "Partial fit", fail: "Doesn't fit" };

export interface ConceptExportModel {
  brand: string;
  conceptCode: string;
  topConceptName: string;
  generatedLabel: string | null;
  confidenceScore: number;
  confidenceLabel: string;
  version: number | null;
  rankedConcepts: {
    rank: number;
    name: string;
    description: string;
    fitLabel: string;
    fitScore: string;
    rationale: string;
  }[];
  candidates: { name: string; vehicleClass: string; description: string; rationale: string }[];
  tradeoffNotes: {
    name: string;
    fitLabel: string;
    fitScore: string;
    prosCons: string[];
    rationale: string;
  }[];
  footer: string;
  fileBase: string;
}

export function buildConceptExportModel(input: ConceptExportInput): ConceptExportModel {
  const version = input.version;
  // Sorted once, up front — both the dashboard's "top concept" and the
  // exported table order must agree on what rank 1 actually is; the input
  // array's own order isn't guaranteed to already be rank-ascending.
  const sortedRanked = [...input.rankedConcepts].sort((a, b) => a.rank - b.rank);
  const top = sortedRanked[0];
  return {
    brand: "TorqWings — The Hangar",
    conceptCode: input.conceptCode,
    topConceptName: top?.conceptName ?? input.conceptCode,
    generatedLabel: input.generatedAt
      ? new Date(input.generatedAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })
      : null,
    confidenceScore: input.confidenceScore,
    confidenceLabel: `${Math.round(input.confidenceScore * 100)}%`,
    version,
    rankedConcepts: sortedRanked.map((r) => ({
        rank: r.rank,
        name: r.conceptName,
        description: r.description,
        fitLabel: FIT_LABEL[r.constraintFit] ?? r.constraintFit,
        fitScore: `${r.fitScore}/10`,
        rationale: r.rationale,
      })),
    candidates: input.candidates.map((c) => ({
      name: c.conceptName,
      vehicleClass: c.vehicleClass,
      description: c.description,
      rationale: c.rationale,
    })),
    tradeoffNotes: input.tradeoffNotes.map((n) => ({
      name: n.conceptName,
      fitLabel: FIT_LABEL[n.constraintFit] ?? n.constraintFit,
      fitScore: `${n.fitScore}/10`,
      prosCons: n.prosCons,
      rationale: n.rationale,
    })),
    footer: `Generated by Concept Agent — Bay 02, The Hangar.${version !== null ? ` Version ${version}.` : ""}`,
    fileBase: `${input.conceptCode.replace(/[^A-Za-z0-9_-]+/g, "_")}-concept-spec${
      version !== null ? `-v${version}` : ""
    }`,
  };
}

// ── PDF ──────────────────────────────────────────────────────────────────

export async function exportConceptPdf(model: ConceptExportModel): Promise<Blob> {
  const [{ jsPDF }, { autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentW = pageW - margin * 2;
  const footerReserve = 30;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin - footerReserve) {
      doc.addPage();
      y = margin;
    }
  };
  const heading = (text: string) => {
    ensureSpace(34);
    doc.setFont("helvetica", "bold").setFontSize(12).setTextColor(20, 40, 70);
    doc.text(pdfSafe(text), margin, y);
    y += 8;
    doc.setDrawColor(200, 205, 215).line(margin, y, pageW - margin, y);
    y += 14;
  };
  const tableEnd = () =>
    ((doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? y) + 22;
  const baseTable = {
    margin: { left: margin, right: margin },
    styles: { font: "helvetica", fontSize: 9, cellPadding: 5, textColor: [40, 45, 55] as [number, number, number] },
    headStyles: { fillColor: [20, 40, 70] as [number, number, number], textColor: 255 },
    alternateRowStyles: { fillColor: [246, 248, 251] as [number, number, number] },
  };

  // Cover / header
  doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(120, 130, 150);
  doc.text(pdfSafe(model.brand.toUpperCase()), margin, y);
  y += 22;
  doc.setFont("helvetica", "bold").setFontSize(20).setTextColor(20, 40, 70);
  const titleLines = doc.splitTextToSize(pdfSafe(model.topConceptName), contentW) as string[];
  doc.text(titleLines, margin, y);
  y += titleLines.length * 24;
  doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(90, 100, 120);
  const meta = [model.conceptCode, model.generatedLabel ? `Generated ${model.generatedLabel}` : null, `Confidence ${model.confidenceLabel}`]
    .filter(Boolean)
    .join("   ·   ");
  doc.text(pdfSafe(meta), margin, y);
  y += 30;

  // Ranked Concepts
  heading(`Ranked Concepts (${model.rankedConcepts.length})`);
  if (model.rankedConcepts.length === 0) {
    doc.setFont("helvetica", "italic").setFontSize(10).setTextColor(110, 115, 125);
    doc.text("No ranked concepts.", margin, y);
    y += 24;
  } else {
    autoTable(doc, {
      ...baseTable,
      startY: y,
      head: [["#", "Concept", "Fit", "Score", "Rationale"]],
      body: model.rankedConcepts.map((r) => [
        String(r.rank),
        pdfSafe(r.name),
        pdfSafe(r.fitLabel),
        r.fitScore,
        pdfSafe(r.rationale),
      ]),
      columnStyles: { 0: { cellWidth: 24 }, 1: { cellWidth: 90, fontStyle: "bold" }, 4: { cellWidth: 200 } },
      didParseCell: (data) => {
        if (data.section === "body" && model.rankedConcepts[data.row.index]?.rank === 1) {
          data.cell.styles.fillColor = [255, 240, 205];
        }
      },
    });
    y = tableEnd();
  }

  // Candidate Concepts (Stage 1 ideation)
  ensureSpace(60);
  heading(`Candidate Concepts (${model.candidates.length})`);
  if (model.candidates.length === 0) {
    doc.setFont("helvetica", "italic").setFontSize(10).setTextColor(110, 115, 125);
    doc.text("No candidate concepts.", margin, y);
    y += 24;
  } else {
    autoTable(doc, {
      ...baseTable,
      startY: y,
      head: [["Concept", "Vehicle class", "Description"]],
      body: model.candidates.map((c) => [pdfSafe(c.name), pdfSafe(c.vehicleClass), pdfSafe(c.description)]),
      columnStyles: { 0: { cellWidth: 110, fontStyle: "bold" }, 1: { cellWidth: 90 } },
    });
    y = tableEnd();
  }

  // Trade-off Notes (Stage 2 reasoning)
  ensureSpace(60);
  heading(`Trade-off Notes (${model.tradeoffNotes.length})`);
  if (model.tradeoffNotes.length === 0) {
    doc.setFont("helvetica", "italic").setFontSize(10).setTextColor(110, 115, 125);
    doc.text("No trade-off notes.", margin, y);
    y += 24;
  } else {
    autoTable(doc, {
      ...baseTable,
      startY: y,
      head: [["Concept", "Fit", "Score", "Pros / cons"]],
      body: model.tradeoffNotes.map((n) => [
        pdfSafe(n.name),
        pdfSafe(n.fitLabel),
        n.fitScore,
        pdfSafe(n.prosCons.join(" · ")),
      ]),
      columnStyles: { 0: { cellWidth: 90, fontStyle: "bold" }, 3: { cellWidth: 220 } },
    });
    y = tableEnd();
  }

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal").setFontSize(8).setTextColor(130, 138, 152);
    doc.text(pdfSafe(model.footer), margin, pageH - margin + 14);
    doc.text(`Page ${p} of ${pages}`, pageW - margin, pageH - margin + 14, { align: "right" });
  }

  return new Blob([doc.output("arraybuffer")], { type: EXPORT_FORMAT_META.pdf.mime });
}

// ── Word ─────────────────────────────────────────────────────────────────

export async function exportConceptDocx(model: ConceptExportModel): Promise<Blob> {
  const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    Table,
    TableRow,
    TableCell,
    WidthType,
    HeadingLevel,
    ShadingType,
    Footer,
    PageNumber,
    AlignmentType,
  } = await import("docx");

  const HEAD_FILL = "142846";
  const cell = (text: string, widthPct: number, opts: { bold?: boolean; fill?: string } = {}) =>
    new TableCell({
      width: { size: widthPct, type: WidthType.PERCENTAGE },
      shading: opts.fill ? { type: ShadingType.CLEAR, fill: opts.fill, color: "auto" } : undefined,
      children: [
        new Paragraph({
          children: [new TextRun({ text, bold: opts.bold, color: opts.fill === HEAD_FILL ? "FFFFFF" : undefined })],
        }),
      ],
    });
  const table = (
    widths: number[],
    head: string[],
    rows: { cells: string[]; boldFirst?: boolean; fill?: string }[],
  ) =>
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({ tableHeader: true, children: head.map((h, i) => cell(h, widths[i], { bold: true, fill: HEAD_FILL })) }),
        ...rows.map(
          (r) =>
            new TableRow({
              children: r.cells.map((c, i) => cell(c, widths[i], { bold: r.boldFirst && i === 0, fill: r.fill })),
            }),
        ),
      ],
    });
  const h2 = (text: string) =>
    new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 120 }, text });
  const note = (text: string) => new Paragraph({ children: [new TextRun({ text, italics: true, color: "6B7280" })] });

  const metaLine = [model.conceptCode, model.generatedLabel ? `Generated ${model.generatedLabel}` : null, `Confidence ${model.confidenceLabel}`]
    .filter(Boolean)
    .join("   ·   ");

  const doc = new Document({
    creator: "TorqWings — The Hangar",
    title: `${model.topConceptName} — ${model.conceptCode}`,
    sections: [
      {
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: `${model.footer}   Page `, size: 16, color: "6B7280" }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "6B7280" }),
                  new TextRun({ text: " of ", size: 16, color: "6B7280" }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: "6B7280" }),
                ],
              }),
            ],
          }),
        },
        children: [
          new Paragraph({ children: [new TextRun({ text: model.brand.toUpperCase(), bold: true, size: 18, color: "78829A" })] }),
          new Paragraph({ heading: HeadingLevel.TITLE, text: model.topConceptName }),
          new Paragraph({ children: [new TextRun({ text: metaLine, color: "5A6478" })] }),

          h2(`Ranked Concepts (${model.rankedConcepts.length})`),
          model.rankedConcepts.length === 0
            ? note("No ranked concepts.")
            : table(
                [8, 24, 16, 12, 40],
                ["#", "Concept", "Fit", "Score", "Rationale"],
                model.rankedConcepts.map((r) => ({
                  cells: [String(r.rank), r.name, r.fitLabel, r.fitScore, r.rationale],
                  boldFirst: true,
                  fill: r.rank === 1 ? "FFF0CD" : undefined,
                })),
              ),

          h2(`Candidate Concepts (${model.candidates.length})`),
          model.candidates.length === 0
            ? note("No candidate concepts.")
            : table(
                [28, 22, 50],
                ["Concept", "Vehicle class", "Description"],
                model.candidates.map((c) => ({ cells: [c.name, c.vehicleClass, c.description], boldFirst: true })),
              ),

          h2(`Trade-off Notes (${model.tradeoffNotes.length})`),
          model.tradeoffNotes.length === 0
            ? note("No trade-off notes.")
            : table(
                [22, 14, 12, 52],
                ["Concept", "Fit", "Score", "Pros / cons"],
                model.tradeoffNotes.map((n) => ({
                  cells: [n.name, n.fitLabel, n.fitScore, n.prosCons.join(" · ")],
                  boldFirst: true,
                })),
              ),
        ],
      },
    ],
  });
  return Packer.toBlob(doc);
}

// ── Excel ────────────────────────────────────────────────────────────────

export async function exportConceptXlsx(model: ConceptExportModel): Promise<Blob> {
  const { default: writeExcelFile } = await import("write-excel-file/universal");
  const head = (...labels: string[]) => labels.map((value) => ({ value, fontWeight: "bold" as const }));

  return writeExcelFile(
    [
      {
        sheet: "Overview",
        columns: [{ width: 24 }, { width: 90 }],
        data: [
          head("Field", "Value"),
          ["Concept code", model.conceptCode],
          ["Top concept", model.topConceptName],
          ["Generated", model.generatedLabel ?? "—"],
          ["Version", model.version ?? "—"],
          ["Confidence score", { value: model.confidenceScore, format: "0%" }],
        ] as never,
      },
      {
        sheet: "Ranked Concepts",
        columns: [{ width: 6 }, { width: 30 }, { width: 14 }, { width: 10 }, { width: 60 }],
        data: [
          head("Rank", "Concept", "Fit", "Score", "Rationale"),
          ...model.rankedConcepts.map((r) => [r.rank, r.name, r.fitLabel, r.fitScore, r.rationale]),
        ] as never,
      },
      {
        sheet: "Candidates",
        columns: [{ width: 30 }, { width: 22 }, { width: 60 }],
        data: [
          head("Concept", "Vehicle class", "Description"),
          ...model.candidates.map((c) => [c.name, c.vehicleClass, c.description]),
        ] as never,
      },
      {
        sheet: "Trade-off Notes",
        columns: [{ width: 30 }, { width: 14 }, { width: 10 }, { width: 60 }],
        data: [
          head("Concept", "Fit", "Score", "Pros / cons"),
          ...model.tradeoffNotes.map((n) => [n.name, n.fitLabel, n.fitScore, n.prosCons.join(" · ")]),
        ] as never,
      },
    ],
  ).toBlob();
}

export async function exportConcept(
  format: MissionExportFormat,
  model: ConceptExportModel,
): Promise<{ blob: Blob; fileName: string }> {
  const blob =
    format === "pdf"
      ? await exportConceptPdf(model)
      : format === "docx"
        ? await exportConceptDocx(model)
        : await exportConceptXlsx(model);
  return { blob, fileName: `${model.fileBase}.${EXPORT_FORMAT_META[format].ext}` };
}
