// Manual verification script for missionExport.ts — generates the real PDF,
// Word and Excel files in Node (the same libraries the browser loads on click)
// and checks their contents. Word and Excel are zip packages, so a tiny zip
// reader (node:zlib) opens them to assert on the actual XML. No LLM, no DB.
// Run directly:
//
//   node src/lib/the-hangar/missionExport.manualtest.ts
import { inflateRawSync } from "node:zlib";
import {
  buildMissionExportModel,
  exportMission,
  formatKpiDisplay,
  isCostKpi,
  orderKpis,
  pdfSafe,
  type MissionExportInput,
} from "./missionExport.ts";

let passCount = 0;
let failCount = 0;

function check(name: string, actual: unknown, expected: unknown): void {
  const pass = JSON.stringify(actual) === JSON.stringify(expected);
  console.log(`${pass ? "PASS" : "FAIL"}  ${name}`);
  if (!pass) {
    console.log(`      expected: ${JSON.stringify(expected)}`);
    console.log(`      actual:   ${JSON.stringify(actual)}`);
  }
  if (pass) passCount++;
  else failCount++;
}

// Minimal zip reader: end-of-central-directory -> central directory -> each
// entry's local header -> inflate. Enough for the .docx / .xlsx these
// libraries write (deflate or stored, no zip64, no encryption).
function readZip(buf: Buffer): Map<string, string> {
  let eocd = -1;
  for (let i = buf.length - 22; i >= 0; i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("not a zip: no end-of-central-directory record");
  const entryCount = buf.readUInt16LE(eocd + 10);
  let p = buf.readUInt32LE(eocd + 16);
  const files = new Map<string, string>();
  for (let n = 0; n < entryCount; n++) {
    if (buf.readUInt32LE(p) !== 0x02014b50) throw new Error("bad central directory entry");
    const method = buf.readUInt16LE(p + 10);
    const compressedSize = buf.readUInt32LE(p + 20);
    const nameLen = buf.readUInt16LE(p + 28);
    const extraLen = buf.readUInt16LE(p + 30);
    const commentLen = buf.readUInt16LE(p + 32);
    const localOffset = buf.readUInt32LE(p + 42);
    const name = buf.toString("utf8", p + 46, p + 46 + nameLen);
    const dataStart = localOffset + 30 + buf.readUInt16LE(localOffset + 26) + buf.readUInt16LE(localOffset + 28);
    const raw = buf.subarray(dataStart, dataStart + compressedSize);
    files.set(name, (method === 8 ? inflateRawSync(raw) : raw).toString("utf8"));
    p += 46 + nameLen + extraLen + commentLen;
  }
  return files;
}

const count = (haystack: string, needle: string): number => haystack.split(needle).length - 1;

const constraints = Array.from({ length: 28 }, (_, i) => ({
  name: `Constraint ${i + 1}: operating envelope limit`,
  value: `${10 + i} units, keep within tolerance ≥ ${i}% — verified`,
  sources: i % 3 === 0 ? ["user", "DOM-001"] : ["inferred"],
}));

const input: MissionExportInput = {
  missionCode: "TW-2609211530-AB12",
  generatedAt: "2026-09-21T10:00:00.000Z",
  confidenceScore: 0.72,
  version: 2,
  missionSpecs: {
    domain: "UAV",
    vertical: null,
    vehicleClass: "Multirotor",
    missionType: "Aerial water drop for forest-fire suppression — Western Ghats",
    phase: "Conceptual",
    operatingEnvironment: "Hot, high-altitude, smoke-affected terrain",
  },
  summary: "A multirotor carrying a 15 kg water payload over 12 km. ".repeat(8),
  constraints,
  kpis: [
    { name: "Range", target: "12", unit: "km", priority: 2 },
    { name: "Payload", target: "15", unit: "kg", priority: "critical" },
    { name: "Budget", target: "500000", unit: "USD", priority: 3 },
    { name: "Endurance", target: "35", unit: "min", priority: "critical" },
    { name: "Unit cost", target: "4,50,000", unit: "INR", priority: 1 },
  ],
  validationFlags: ["endurance: no value extracted or provided", "range 12 km is within bounds"],
};

console.log("--- shared display rules ---");

check("a cost KPI in a non-INR unit is flagged for the ₹ override", isCostKpi("Budget", "USD"), true);
check("...but not when the unit is already INR / ₹", [isCostKpi("Unit cost", "INR"), isCostKpi("Budget", "₹")], [false, false]);
check("non-cost KPIs are untouched", isCostKpi("Payload", "kg"), false);
check("₹ override: Budget in USD shows ₹500000", formatKpiDisplay("Budget", "500000", "USD"), "₹500000");
check("normal KPI: target + unit", formatKpiDisplay("Payload", "15", "kg"), "15 kg");
check(
  "KPI order: gate-tier first, then ranked ascending",
  orderKpis(input.kpis).map((k) => k.name),
  ["Payload", "Endurance", "Unit cost", "Range", "Budget"],
);
check("ordering doesn't mutate the input", input.kpis.map((k) => k.name)[0], "Range");

console.log("\n--- model ---");

const model = buildMissionExportModel(input);
check("footer carries the spec version", model.footer, "Generated by Mission Agent — Bay 01, The Hangar. Version 2.");
check("file name is sanitised and versioned", model.fileBase, "TW-2609211530-AB12-mission-spec-v2");
check("confidence label is a whole-number percent", model.confidenceLabel, "72%");
check("constraint sources are joined", model.constraints[0].sources, "user, DOM-001");
check("empty vertical shows a dash, not 'null'", model.specRows.find((r) => r.label === "Vertical")?.value, "—");
check("KPI tiers: GATE for critical, P<n> for ranked", model.kpis.map((k) => k.tier), ["GATE", "GATE", "P1", "P2", "P3"]);
check("the ₹ override reaches the model's display", model.kpis.find((k) => k.name === "Budget")?.display, "₹500000");

const noVersion = buildMissionExportModel({ ...input, version: null, generatedAt: null });
check(
  "an unknown version is omitted from the footer and the file name",
  [noVersion.footer, noVersion.fileBase, noVersion.generatedLabel],
  ["Generated by Mission Agent — Bay 01, The Hangar.", "TW-2609211530-AB12-mission-spec", null],
);
check(
  "a hostile mission code can't escape the file name",
  buildMissionExportModel({ ...input, missionCode: "../../x y\\z.pdf" }).fileBase.includes("/"),
  false,
);

console.log("\n--- pdfSafe (PDF's built-in font has no ₹ or math symbols) ---");

check("₹ -> INR", pdfSafe("₹5"), "INR 5");
check("≥ ≤ → ≈ … become ASCII", pdfSafe("≥ ≤ → ≈ …"), ">= <= -> ~ ...");
check("dashes and curly quotes become plain", pdfSafe("a — b – c ‘q’ “d”"), "a - b - c 'q' \"d\"");
check("Latin-1 text is left alone", pdfSafe("café 5 °C × 2"), "café 5 °C × 2");
check("an unsupported glyph becomes '?', not garbage", pdfSafe("日本"), "??");

console.log("\n--- generated files ---");

const files: Record<string, Buffer> = {};
for (const format of ["pdf", "docx", "xlsx"] as const) {
  const { blob, fileName } = await exportMission(format, model);
  files[format] = Buffer.from(await blob.arrayBuffer());
  check(`${format}: file name`, fileName, `TW-2609211530-AB12-mission-spec-v2.${format}`);
}

// PDF
const pdfText = files.pdf.toString("latin1");
check("pdf: starts with the PDF header", pdfText.startsWith("%PDF-"), true);
// "/Type /Page" is also a prefix of "/Type /Pages", so exclude that.
check("pdf: exactly 3 pages for 28 constraints", (pdfText.match(/\/Type \/Page(?!s)/g) ?? []).length, 3);
check("pdf: footer with the version is in the file", pdfText.includes("Version 2."), true);
check("pdf: ₹ was written as INR (no missing glyph)", pdfText.includes("INR 500000") && !pdfText.includes("₹"), true);

// Word
const docx = readZip(files.docx);
const docXml = docx.get("word/document.xml") ?? "";
check("docx: core parts present", ["word/document.xml", "word/footer1.xml", "[Content_Types].xml"].every((n) => docx.has(n)), true);
check("docx: three tables (spec, constraints, KPIs)", count(docXml, "<w:tbl>"), 3);
check("docx: every table repeats its header row across pages", count(docXml, "<w:tblHeader"), 3);
check("docx: ₹ and ≥ are kept (Word is Unicode)", docXml.includes("₹500000") && docXml.includes("≥"), true);
check("docx: an INR-unit KPI isn't double-converted", docXml.includes("4,50,000 INR"), true);
check("docx: 2 gate-tier KPI rows are shaded (3 cells each)", count(docXml, 'w:fill="FFF0CD"'), 6);
check("docx: validation notes are bullets", count(docXml, "<w:numPr>"), 2);
const kpiOrder = ["Payload", "Endurance", "Unit cost", "Range", "Budget"].map((n) => docXml.lastIndexOf(`>${n}<`));
check("docx: KPI rows appear gate-tier first", kpiOrder.every((v, i) => i === 0 || v > kpiOrder[i - 1]), true);
const footXml = docx.get("word/footer1.xml") ?? "";
check("docx: footer has the version and live page-number fields", footXml.includes("Version 2.") && footXml.includes("PAGE") && footXml.includes("NUMPAGES"), true);

// Excel
const xlsx = readZip(files.xlsx);
const wbXml = xlsx.get("xl/workbook.xml") ?? "";
const strings = xlsx.get("xl/sharedStrings.xml") ?? "";
check("xlsx: three sheets, named per the spec", ["Overview", "Constraints", "KPIs"].every((n) => wbXml.includes(`name="${n}"`)), true);
check("xlsx: exactly 3 worksheets", [...xlsx.keys()].filter((k) => /^xl\/worksheets\/sheet\d+\.xml$/.test(k)).length, 3);
check("xlsx: KPI priority column carries 'critical'", strings.includes(">critical<"), true);
check("xlsx: ₹ unit override present", strings.includes(">₹<"), true);
check("xlsx: multi-line validation notes are kept", strings.includes("endurance: no value extracted or provided"), true);
const overview = xlsx.get("xl/worksheets/sheet1.xml") ?? "";
check("xlsx: confidence is stored as a number (0.72), not text", overview.includes("<v>0.72</v>"), true);
check("xlsx: Overview has 13 rows (header, 5 meta, 6 spec, notes)", count(overview, "<row "), 13);
check("xlsx: Constraints has 29 rows (header + 28)", count(xlsx.get("xl/worksheets/sheet2.xml") ?? "", "<row "), 29);
check("xlsx: KPIs has 6 rows (header + 5)", count(xlsx.get("xl/worksheets/sheet3.xml") ?? "", "<row "), 6);

console.log("\n--- empty spec still exports in every format ---");

const empty = buildMissionExportModel({ ...input, constraints: [], kpis: [], validationFlags: [], summary: "Short." });
for (const format of ["pdf", "docx", "xlsx"] as const) {
  let ok = true;
  let bytes = 0;
  try {
    bytes = (await (await exportMission(format, empty)).blob.arrayBuffer()).byteLength;
  } catch {
    ok = false;
  }
  check(`${format}: no constraints / KPIs / notes`, ok && bytes > 500, true);
}
const emptyDoc = readZip(Buffer.from(await (await exportMission("docx", empty)).blob.arrayBuffer())).get("word/document.xml") ?? "";
check("docx (empty): only the spec table; the empty sections say so", count(emptyDoc, "<w:tbl>") === 1 && emptyDoc.includes("No constraints identified.") && emptyDoc.includes("No KPIs derived."), true);

console.log(`\n${passCount} passed, ${failCount} failed`);
if (failCount > 0) process.exit(1);
