/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as MissionHubRouteImport } from './routes/mission-hub'
import { Route as FieldRouteImport } from './routes/field'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PilotIndexRouteImport } from './routes/pilot.index'
import { Route as ControlCenterIndexRouteImport } from './routes/control-center.index'
import { Route as PilotTrackingRouteImport } from './routes/pilot.tracking'
import { Route as PilotSyncRouteImport } from './routes/pilot.sync'
import { Route as PilotProfileRouteImport } from './routes/pilot.profile'
import { Route as PilotLoginRouteImport } from './routes/pilot.login'
import { Route as MissionHubWaitlistRouteImport } from './routes/mission-hub.waitlist'
import { Route as MissionHubUsersRouteImport } from './routes/mission-hub.users'
import { Route as MissionHubSettingsRouteImport } from './routes/mission-hub.settings'
import { Route as MissionHubResetPasswordRouteImport } from './routes/mission-hub.reset-password'
import { Route as MissionHubLoginRouteImport } from './routes/mission-hub.login'
import { Route as MissionHubDesignStudioRouteImport } from './routes/mission-hub.design-studio'
import { Route as MissionHubDashboardRouteImport } from './routes/mission-hub.dashboard'
import { Route as MissionHubContactsRouteImport } from './routes/mission-hub.contacts'
import { Route as ControlCenterUsersRouteImport } from './routes/control-center.users'
import { Route as ControlCenterLoginRouteImport } from './routes/control-center.login'
import { Route as ControlCenterAgriskyRouteImport } from './routes/control-center.agrisky'
import { Route as ControlCenterAerospawnDesignStudioRouteImport } from './routes/control-center.aerospawn-design-studio'
import { Route as PilotMissionsIndexRouteImport } from './routes/pilot.missions.index'
import { Route as ControlCenterAerospawnDesignStudioIndexRouteImport } from './routes/control-center.aerospawn-design-studio.index'
import { Route as PilotMissionsIdRouteImport } from './routes/pilot.missions.$id'
import { Route as MissionHubVerticalsVerticalRouteImport } from './routes/mission-hub.verticals.$vertical'
import { Route as ControlCenterAerospawnDesignStudioSimulationRouteImport } from './routes/control-center.aerospawn-design-studio.simulation'
import { Route as ControlCenterAerospawnDesignStudioRequirementsRouteImport } from './routes/control-center.aerospawn-design-studio.requirements'
import { Route as ControlCenterAerospawnDesignStudioReportRouteImport } from './routes/control-center.aerospawn-design-studio.report'
import { Route as ControlCenterAerospawnDesignStudioNewRouteImport } from './routes/control-center.aerospawn-design-studio.new'
import { Route as ControlCenterAerospawnDesignStudioHistoryRouteImport } from './routes/control-center.aerospawn-design-studio.history'
import { Route as ControlCenterAerospawnDesignStudioDesignRouteImport } from './routes/control-center.aerospawn-design-studio.design'
import { Route as ControlCenterAerospawnDesignStudioComponentsRouteImport } from './routes/control-center.aerospawn-design-studio.components'
import { Route as ControlCenterAerospawnDesignStudioComplianceRouteImport } from './routes/control-center.aerospawn-design-studio.compliance'
import { Route as ControlCenterAerospawnDesignStudioAdvisorRouteImport } from './routes/control-center.aerospawn-design-studio.advisor'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionHubRoute = MissionHubRouteImport.update({
  id: '/mission-hub',
  path: '/mission-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotIndexRoute = PilotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PilotRoute,
} as any)
const ControlCenterIndexRoute = ControlCenterIndexRouteImport.update({
  id: '/control-center/',
  path: '/control-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotTrackingRoute = PilotTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => PilotRoute,
} as any)
const PilotSyncRoute = PilotSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => PilotRoute,
} as any)
const PilotProfileRoute = PilotProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PilotRoute,
} as any)
const PilotLoginRoute = PilotLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PilotRoute,
} as any)
const MissionHubWaitlistRoute = MissionHubWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => MissionHubRoute,
} as any)
const MissionHubUsersRoute = MissionHubUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MissionHubRoute,
} as any)
const MissionHubSettingsRoute = MissionHubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MissionHubRoute,
} as any)
const MissionHubResetPasswordRoute = MissionHubResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MissionHubRoute,
} as any)
const MissionHubLoginRoute = MissionHubLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MissionHubRoute,
} as any)
const MissionHubDesignStudioRoute = MissionHubDesignStudioRouteImport.update({
  id: '/design-studio',
  path: '/design-studio',
  getParentRoute: () => MissionHubRoute,
} as any)
const MissionHubDashboardRoute = MissionHubDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MissionHubRoute,
} as any)
const MissionHubContactsRoute = MissionHubContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => MissionHubRoute,
} as any)
const ControlCenterUsersRoute = ControlCenterUsersRouteImport.update({
  id: '/control-center/users',
  path: '/control-center/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterLoginRoute = ControlCenterLoginRouteImport.update({
  id: '/control-center/login',
  path: '/control-center/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterAgriskyRoute = ControlCenterAgriskyRouteImport.update({
  id: '/control-center/agrisky',
  path: '/control-center/agrisky',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterAerospawnDesignStudioRoute =
  ControlCenterAerospawnDesignStudioRouteImport.update({
    id: '/control-center/aerospawn-design-studio',
    path: '/control-center/aerospawn-design-studio',
    getParentRoute: () => rootRouteImport,
  } as any)
const PilotMissionsIndexRoute = PilotMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => PilotRoute,
} as any)
const ControlCenterAerospawnDesignStudioIndexRoute =
  ControlCenterAerospawnDesignStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const PilotMissionsIdRoute = PilotMissionsIdRouteImport.update({
  id: '/missions/$id',
  path: '/missions/$id',
  getParentRoute: () => PilotRoute,
} as any)
const MissionHubVerticalsVerticalRoute =
  MissionHubVerticalsVerticalRouteImport.update({
    id: '/verticals/$vertical',
    path: '/verticals/$vertical',
    getParentRoute: () => MissionHubRoute,
  } as any)
const ControlCenterAerospawnDesignStudioSimulationRoute =
  ControlCenterAerospawnDesignStudioSimulationRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioRequirementsRoute =
  ControlCenterAerospawnDesignStudioRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioReportRoute =
  ControlCenterAerospawnDesignStudioReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioNewRoute =
  ControlCenterAerospawnDesignStudioNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioHistoryRoute =
  ControlCenterAerospawnDesignStudioHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioDesignRoute =
  ControlCenterAerospawnDesignStudioDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioComponentsRoute =
  ControlCenterAerospawnDesignStudioComponentsRouteImport.update({
    id: '/components',
    path: '/components',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioComplianceRoute =
  ControlCenterAerospawnDesignStudioComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)
const ControlCenterAerospawnDesignStudioAdvisorRoute =
  ControlCenterAerospawnDesignStudioAdvisorRouteImport.update({
    id: '/advisor',
    path: '/advisor',
    getParentRoute: () => ControlCenterAerospawnDesignStudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/field': typeof FieldRoute
  '/mission-hub': typeof MissionHubRouteWithChildren
  '/pilot': typeof PilotRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/control-center/aerospawn-design-studio': typeof ControlCenterAerospawnDesignStudioRouteWithChildren
  '/control-center/agrisky': typeof ControlCenterAgriskyRoute
  '/control-center/login': typeof ControlCenterLoginRoute
  '/control-center/users': typeof ControlCenterUsersRoute
  '/mission-hub/contacts': typeof MissionHubContactsRoute
  '/mission-hub/dashboard': typeof MissionHubDashboardRoute
  '/mission-hub/design-studio': typeof MissionHubDesignStudioRoute
  '/mission-hub/login': typeof MissionHubLoginRoute
  '/mission-hub/reset-password': typeof MissionHubResetPasswordRoute
  '/mission-hub/settings': typeof MissionHubSettingsRoute
  '/mission-hub/users': typeof MissionHubUsersRoute
  '/mission-hub/waitlist': typeof MissionHubWaitlistRoute
  '/pilot/login': typeof PilotLoginRoute
  '/pilot/profile': typeof PilotProfileRoute
  '/pilot/sync': typeof PilotSyncRoute
  '/pilot/tracking': typeof PilotTrackingRoute
  '/control-center/': typeof ControlCenterIndexRoute
  '/pilot/': typeof PilotIndexRoute
  '/control-center/aerospawn-design-studio/advisor': typeof ControlCenterAerospawnDesignStudioAdvisorRoute
  '/control-center/aerospawn-design-studio/compliance': typeof ControlCenterAerospawnDesignStudioComplianceRoute
  '/control-center/aerospawn-design-studio/components': typeof ControlCenterAerospawnDesignStudioComponentsRoute
  '/control-center/aerospawn-design-studio/design': typeof ControlCenterAerospawnDesignStudioDesignRoute
  '/control-center/aerospawn-design-studio/history': typeof ControlCenterAerospawnDesignStudioHistoryRoute
  '/control-center/aerospawn-design-studio/new': typeof ControlCenterAerospawnDesignStudioNewRoute
  '/control-center/aerospawn-design-studio/report': typeof ControlCenterAerospawnDesignStudioReportRoute
  '/control-center/aerospawn-design-studio/requirements': typeof ControlCenterAerospawnDesignStudioRequirementsRoute
  '/control-center/aerospawn-design-studio/simulation': typeof ControlCenterAerospawnDesignStudioSimulationRoute
  '/mission-hub/verticals/$vertical': typeof MissionHubVerticalsVerticalRoute
  '/pilot/missions/$id': typeof PilotMissionsIdRoute
  '/control-center/aerospawn-design-studio/': typeof ControlCenterAerospawnDesignStudioIndexRoute
  '/pilot/missions/': typeof PilotMissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/field': typeof FieldRoute
  '/mission-hub': typeof MissionHubRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/control-center/agrisky': typeof ControlCenterAgriskyRoute
  '/control-center/login': typeof ControlCenterLoginRoute
  '/control-center/users': typeof ControlCenterUsersRoute
  '/mission-hub/contacts': typeof MissionHubContactsRoute
  '/mission-hub/dashboard': typeof MissionHubDashboardRoute
  '/mission-hub/design-studio': typeof MissionHubDesignStudioRoute
  '/mission-hub/login': typeof MissionHubLoginRoute
  '/mission-hub/reset-password': typeof MissionHubResetPasswordRoute
  '/mission-hub/settings': typeof MissionHubSettingsRoute
  '/mission-hub/users': typeof MissionHubUsersRoute
  '/mission-hub/waitlist': typeof MissionHubWaitlistRoute
  '/pilot/login': typeof PilotLoginRoute
  '/pilot/profile': typeof PilotProfileRoute
  '/pilot/sync': typeof PilotSyncRoute
  '/pilot/tracking': typeof PilotTrackingRoute
  '/control-center': typeof ControlCenterIndexRoute
  '/pilot': typeof PilotIndexRoute
  '/control-center/aerospawn-design-studio/advisor': typeof ControlCenterAerospawnDesignStudioAdvisorRoute
  '/control-center/aerospawn-design-studio/compliance': typeof ControlCenterAerospawnDesignStudioComplianceRoute
  '/control-center/aerospawn-design-studio/components': typeof ControlCenterAerospawnDesignStudioComponentsRoute
  '/control-center/aerospawn-design-studio/design': typeof ControlCenterAerospawnDesignStudioDesignRoute
  '/control-center/aerospawn-design-studio/history': typeof ControlCenterAerospawnDesignStudioHistoryRoute
  '/control-center/aerospawn-design-studio/new': typeof ControlCenterAerospawnDesignStudioNewRoute
  '/control-center/aerospawn-design-studio/report': typeof ControlCenterAerospawnDesignStudioReportRoute
  '/control-center/aerospawn-design-studio/requirements': typeof ControlCenterAerospawnDesignStudioRequirementsRoute
  '/control-center/aerospawn-design-studio/simulation': typeof ControlCenterAerospawnDesignStudioSimulationRoute
  '/mission-hub/verticals/$vertical': typeof MissionHubVerticalsVerticalRoute
  '/pilot/missions/$id': typeof PilotMissionsIdRoute
  '/control-center/aerospawn-design-studio': typeof ControlCenterAerospawnDesignStudioIndexRoute
  '/pilot/missions': typeof PilotMissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/field': typeof FieldRoute
  '/mission-hub': typeof MissionHubRouteWithChildren
  '/pilot': typeof PilotRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/control-center/aerospawn-design-studio': typeof ControlCenterAerospawnDesignStudioRouteWithChildren
  '/control-center/agrisky': typeof ControlCenterAgriskyRoute
  '/control-center/login': typeof ControlCenterLoginRoute
  '/control-center/users': typeof ControlCenterUsersRoute
  '/mission-hub/contacts': typeof MissionHubContactsRoute
  '/mission-hub/dashboard': typeof MissionHubDashboardRoute
  '/mission-hub/design-studio': typeof MissionHubDesignStudioRoute
  '/mission-hub/login': typeof MissionHubLoginRoute
  '/mission-hub/reset-password': typeof MissionHubResetPasswordRoute
  '/mission-hub/settings': typeof MissionHubSettingsRoute
  '/mission-hub/users': typeof MissionHubUsersRoute
  '/mission-hub/waitlist': typeof MissionHubWaitlistRoute
  '/pilot/login': typeof PilotLoginRoute
  '/pilot/profile': typeof PilotProfileRoute
  '/pilot/sync': typeof PilotSyncRoute
  '/pilot/tracking': typeof PilotTrackingRoute
  '/control-center/': typeof ControlCenterIndexRoute
  '/pilot/': typeof PilotIndexRoute
  '/control-center/aerospawn-design-studio/advisor': typeof ControlCenterAerospawnDesignStudioAdvisorRoute
  '/control-center/aerospawn-design-studio/compliance': typeof ControlCenterAerospawnDesignStudioComplianceRoute
  '/control-center/aerospawn-design-studio/components': typeof ControlCenterAerospawnDesignStudioComponentsRoute
  '/control-center/aerospawn-design-studio/design': typeof ControlCenterAerospawnDesignStudioDesignRoute
  '/control-center/aerospawn-design-studio/history': typeof ControlCenterAerospawnDesignStudioHistoryRoute
  '/control-center/aerospawn-design-studio/new': typeof ControlCenterAerospawnDesignStudioNewRoute
  '/control-center/aerospawn-design-studio/report': typeof ControlCenterAerospawnDesignStudioReportRoute
  '/control-center/aerospawn-design-studio/requirements': typeof ControlCenterAerospawnDesignStudioRequirementsRoute
  '/control-center/aerospawn-design-studio/simulation': typeof ControlCenterAerospawnDesignStudioSimulationRoute
  '/mission-hub/verticals/$vertical': typeof MissionHubVerticalsVerticalRoute
  '/pilot/missions/$id': typeof PilotMissionsIdRoute
  '/control-center/aerospawn-design-studio/': typeof ControlCenterAerospawnDesignStudioIndexRoute
  '/pilot/missions/': typeof PilotMissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/field'
    | '/mission-hub'
    | '/pilot'
    | '/sitemap.xml'
    | '/control-center/aerospawn-design-studio'
    | '/control-center/agrisky'
    | '/control-center/login'
    | '/control-center/users'
    | '/mission-hub/contacts'
    | '/mission-hub/dashboard'
    | '/mission-hub/design-studio'
    | '/mission-hub/login'
    | '/mission-hub/reset-password'
    | '/mission-hub/settings'
    | '/mission-hub/users'
    | '/mission-hub/waitlist'
    | '/pilot/login'
    | '/pilot/profile'
    | '/pilot/sync'
    | '/pilot/tracking'
    | '/control-center/'
    | '/pilot/'
    | '/control-center/aerospawn-design-studio/advisor'
    | '/control-center/aerospawn-design-studio/compliance'
    | '/control-center/aerospawn-design-studio/components'
    | '/control-center/aerospawn-design-studio/design'
    | '/control-center/aerospawn-design-studio/history'
    | '/control-center/aerospawn-design-studio/new'
    | '/control-center/aerospawn-design-studio/report'
    | '/control-center/aerospawn-design-studio/requirements'
    | '/control-center/aerospawn-design-studio/simulation'
    | '/mission-hub/verticals/$vertical'
    | '/pilot/missions/$id'
    | '/control-center/aerospawn-design-studio/'
    | '/pilot/missions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/field'
    | '/mission-hub'
    | '/sitemap.xml'
    | '/control-center/agrisky'
    | '/control-center/login'
    | '/control-center/users'
    | '/mission-hub/contacts'
    | '/mission-hub/dashboard'
    | '/mission-hub/design-studio'
    | '/mission-hub/login'
    | '/mission-hub/reset-password'
    | '/mission-hub/settings'
    | '/mission-hub/users'
    | '/mission-hub/waitlist'
    | '/pilot/login'
    | '/pilot/profile'
    | '/pilot/sync'
    | '/pilot/tracking'
    | '/control-center'
    | '/pilot'
    | '/control-center/aerospawn-design-studio/advisor'
    | '/control-center/aerospawn-design-studio/compliance'
    | '/control-center/aerospawn-design-studio/components'
    | '/control-center/aerospawn-design-studio/design'
    | '/control-center/aerospawn-design-studio/history'
    | '/control-center/aerospawn-design-studio/new'
    | '/control-center/aerospawn-design-studio/report'
    | '/control-center/aerospawn-design-studio/requirements'
    | '/control-center/aerospawn-design-studio/simulation'
    | '/mission-hub/verticals/$vertical'
    | '/pilot/missions/$id'
    | '/control-center/aerospawn-design-studio'
    | '/pilot/missions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/field'
    | '/mission-hub'
    | '/pilot'
    | '/sitemap.xml'
    | '/control-center/aerospawn-design-studio'
    | '/control-center/agrisky'
    | '/control-center/login'
    | '/control-center/users'
    | '/mission-hub/contacts'
    | '/mission-hub/dashboard'
    | '/mission-hub/design-studio'
    | '/mission-hub/login'
    | '/mission-hub/reset-password'
    | '/mission-hub/settings'
    | '/mission-hub/users'
    | '/mission-hub/waitlist'
    | '/pilot/login'
    | '/pilot/profile'
    | '/pilot/sync'
    | '/pilot/tracking'
    | '/control-center/'
    | '/pilot/'
    | '/control-center/aerospawn-design-studio/advisor'
    | '/control-center/aerospawn-design-studio/compliance'
    | '/control-center/aerospawn-design-studio/components'
    | '/control-center/aerospawn-design-studio/design'
    | '/control-center/aerospawn-design-studio/history'
    | '/control-center/aerospawn-design-studio/new'
    | '/control-center/aerospawn-design-studio/report'
    | '/control-center/aerospawn-design-studio/requirements'
    | '/control-center/aerospawn-design-studio/simulation'
    | '/mission-hub/verticals/$vertical'
    | '/pilot/missions/$id'
    | '/control-center/aerospawn-design-studio/'
    | '/pilot/missions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FieldRoute: typeof FieldRoute
  MissionHubRoute: typeof MissionHubRouteWithChildren
  PilotRoute: typeof PilotRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ControlCenterAerospawnDesignStudioRoute: typeof ControlCenterAerospawnDesignStudioRouteWithChildren
  ControlCenterAgriskyRoute: typeof ControlCenterAgriskyRoute
  ControlCenterLoginRoute: typeof ControlCenterLoginRoute
  ControlCenterUsersRoute: typeof ControlCenterUsersRoute
  ControlCenterIndexRoute: typeof ControlCenterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-hub': {
      id: '/mission-hub'
      path: '/mission-hub'
      fullPath: '/mission-hub'
      preLoaderRoute: typeof MissionHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/': {
      id: '/pilot/'
      path: '/'
      fullPath: '/pilot/'
      preLoaderRoute: typeof PilotIndexRouteImport
      parentRoute: typeof PilotRoute
    }
    '/control-center/': {
      id: '/control-center/'
      path: '/control-center'
      fullPath: '/control-center/'
      preLoaderRoute: typeof ControlCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/tracking': {
      id: '/pilot/tracking'
      path: '/tracking'
      fullPath: '/pilot/tracking'
      preLoaderRoute: typeof PilotTrackingRouteImport
      parentRoute: typeof PilotRoute
    }
    '/pilot/sync': {
      id: '/pilot/sync'
      path: '/sync'
      fullPath: '/pilot/sync'
      preLoaderRoute: typeof PilotSyncRouteImport
      parentRoute: typeof PilotRoute
    }
    '/pilot/profile': {
      id: '/pilot/profile'
      path: '/profile'
      fullPath: '/pilot/profile'
      preLoaderRoute: typeof PilotProfileRouteImport
      parentRoute: typeof PilotRoute
    }
    '/pilot/login': {
      id: '/pilot/login'
      path: '/login'
      fullPath: '/pilot/login'
      preLoaderRoute: typeof PilotLoginRouteImport
      parentRoute: typeof PilotRoute
    }
    '/mission-hub/waitlist': {
      id: '/mission-hub/waitlist'
      path: '/waitlist'
      fullPath: '/mission-hub/waitlist'
      preLoaderRoute: typeof MissionHubWaitlistRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/mission-hub/users': {
      id: '/mission-hub/users'
      path: '/users'
      fullPath: '/mission-hub/users'
      preLoaderRoute: typeof MissionHubUsersRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/mission-hub/settings': {
      id: '/mission-hub/settings'
      path: '/settings'
      fullPath: '/mission-hub/settings'
      preLoaderRoute: typeof MissionHubSettingsRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/mission-hub/reset-password': {
      id: '/mission-hub/reset-password'
      path: '/reset-password'
      fullPath: '/mission-hub/reset-password'
      preLoaderRoute: typeof MissionHubResetPasswordRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/mission-hub/login': {
      id: '/mission-hub/login'
      path: '/login'
      fullPath: '/mission-hub/login'
      preLoaderRoute: typeof MissionHubLoginRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/mission-hub/design-studio': {
      id: '/mission-hub/design-studio'
      path: '/design-studio'
      fullPath: '/mission-hub/design-studio'
      preLoaderRoute: typeof MissionHubDesignStudioRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/mission-hub/dashboard': {
      id: '/mission-hub/dashboard'
      path: '/dashboard'
      fullPath: '/mission-hub/dashboard'
      preLoaderRoute: typeof MissionHubDashboardRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/mission-hub/contacts': {
      id: '/mission-hub/contacts'
      path: '/contacts'
      fullPath: '/mission-hub/contacts'
      preLoaderRoute: typeof MissionHubContactsRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/control-center/users': {
      id: '/control-center/users'
      path: '/control-center/users'
      fullPath: '/control-center/users'
      preLoaderRoute: typeof ControlCenterUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/login': {
      id: '/control-center/login'
      path: '/control-center/login'
      fullPath: '/control-center/login'
      preLoaderRoute: typeof ControlCenterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/agrisky': {
      id: '/control-center/agrisky'
      path: '/control-center/agrisky'
      fullPath: '/control-center/agrisky'
      preLoaderRoute: typeof ControlCenterAgriskyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/aerospawn-design-studio': {
      id: '/control-center/aerospawn-design-studio'
      path: '/control-center/aerospawn-design-studio'
      fullPath: '/control-center/aerospawn-design-studio'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/missions/': {
      id: '/pilot/missions/'
      path: '/missions'
      fullPath: '/pilot/missions/'
      preLoaderRoute: typeof PilotMissionsIndexRouteImport
      parentRoute: typeof PilotRoute
    }
    '/control-center/aerospawn-design-studio/': {
      id: '/control-center/aerospawn-design-studio/'
      path: '/'
      fullPath: '/control-center/aerospawn-design-studio/'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioIndexRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/pilot/missions/$id': {
      id: '/pilot/missions/$id'
      path: '/missions/$id'
      fullPath: '/pilot/missions/$id'
      preLoaderRoute: typeof PilotMissionsIdRouteImport
      parentRoute: typeof PilotRoute
    }
    '/mission-hub/verticals/$vertical': {
      id: '/mission-hub/verticals/$vertical'
      path: '/verticals/$vertical'
      fullPath: '/mission-hub/verticals/$vertical'
      preLoaderRoute: typeof MissionHubVerticalsVerticalRouteImport
      parentRoute: typeof MissionHubRoute
    }
    '/control-center/aerospawn-design-studio/simulation': {
      id: '/control-center/aerospawn-design-studio/simulation'
      path: '/simulation'
      fullPath: '/control-center/aerospawn-design-studio/simulation'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioSimulationRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/requirements': {
      id: '/control-center/aerospawn-design-studio/requirements'
      path: '/requirements'
      fullPath: '/control-center/aerospawn-design-studio/requirements'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioRequirementsRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/report': {
      id: '/control-center/aerospawn-design-studio/report'
      path: '/report'
      fullPath: '/control-center/aerospawn-design-studio/report'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioReportRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/new': {
      id: '/control-center/aerospawn-design-studio/new'
      path: '/new'
      fullPath: '/control-center/aerospawn-design-studio/new'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioNewRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/history': {
      id: '/control-center/aerospawn-design-studio/history'
      path: '/history'
      fullPath: '/control-center/aerospawn-design-studio/history'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioHistoryRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/design': {
      id: '/control-center/aerospawn-design-studio/design'
      path: '/design'
      fullPath: '/control-center/aerospawn-design-studio/design'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioDesignRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/components': {
      id: '/control-center/aerospawn-design-studio/components'
      path: '/components'
      fullPath: '/control-center/aerospawn-design-studio/components'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioComponentsRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/compliance': {
      id: '/control-center/aerospawn-design-studio/compliance'
      path: '/compliance'
      fullPath: '/control-center/aerospawn-design-studio/compliance'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioComplianceRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
    '/control-center/aerospawn-design-studio/advisor': {
      id: '/control-center/aerospawn-design-studio/advisor'
      path: '/advisor'
      fullPath: '/control-center/aerospawn-design-studio/advisor'
      preLoaderRoute: typeof ControlCenterAerospawnDesignStudioAdvisorRouteImport
      parentRoute: typeof ControlCenterAerospawnDesignStudioRoute
    }
  }
}

interface MissionHubRouteChildren {
  MissionHubContactsRoute: typeof MissionHubContactsRoute
  MissionHubDashboardRoute: typeof MissionHubDashboardRoute
  MissionHubDesignStudioRoute: typeof MissionHubDesignStudioRoute
  MissionHubLoginRoute: typeof MissionHubLoginRoute
  MissionHubResetPasswordRoute: typeof MissionHubResetPasswordRoute
  MissionHubSettingsRoute: typeof MissionHubSettingsRoute
  MissionHubUsersRoute: typeof MissionHubUsersRoute
  MissionHubWaitlistRoute: typeof MissionHubWaitlistRoute
  MissionHubVerticalsVerticalRoute: typeof MissionHubVerticalsVerticalRoute
}

const MissionHubRouteChildren: MissionHubRouteChildren = {
  MissionHubContactsRoute: MissionHubContactsRoute,
  MissionHubDashboardRoute: MissionHubDashboardRoute,
  MissionHubDesignStudioRoute: MissionHubDesignStudioRoute,
  MissionHubLoginRoute: MissionHubLoginRoute,
  MissionHubResetPasswordRoute: MissionHubResetPasswordRoute,
  MissionHubSettingsRoute: MissionHubSettingsRoute,
  MissionHubUsersRoute: MissionHubUsersRoute,
  MissionHubWaitlistRoute: MissionHubWaitlistRoute,
  MissionHubVerticalsVerticalRoute: MissionHubVerticalsVerticalRoute,
}

const MissionHubRouteWithChildren = MissionHubRoute._addFileChildren(
  MissionHubRouteChildren,
)

interface PilotRouteChildren {
  PilotLoginRoute: typeof PilotLoginRoute
  PilotProfileRoute: typeof PilotProfileRoute
  PilotSyncRoute: typeof PilotSyncRoute
  PilotTrackingRoute: typeof PilotTrackingRoute
  PilotIndexRoute: typeof PilotIndexRoute
  PilotMissionsIdRoute: typeof PilotMissionsIdRoute
  PilotMissionsIndexRoute: typeof PilotMissionsIndexRoute
}

const PilotRouteChildren: PilotRouteChildren = {
  PilotLoginRoute: PilotLoginRoute,
  PilotProfileRoute: PilotProfileRoute,
  PilotSyncRoute: PilotSyncRoute,
  PilotTrackingRoute: PilotTrackingRoute,
  PilotIndexRoute: PilotIndexRoute,
  PilotMissionsIdRoute: PilotMissionsIdRoute,
  PilotMissionsIndexRoute: PilotMissionsIndexRoute,
}

const PilotRouteWithChildren = PilotRoute._addFileChildren(PilotRouteChildren)

interface ControlCenterAerospawnDesignStudioRouteChildren {
  ControlCenterAerospawnDesignStudioAdvisorRoute: typeof ControlCenterAerospawnDesignStudioAdvisorRoute
  ControlCenterAerospawnDesignStudioComplianceRoute: typeof ControlCenterAerospawnDesignStudioComplianceRoute
  ControlCenterAerospawnDesignStudioComponentsRoute: typeof ControlCenterAerospawnDesignStudioComponentsRoute
  ControlCenterAerospawnDesignStudioDesignRoute: typeof ControlCenterAerospawnDesignStudioDesignRoute
  ControlCenterAerospawnDesignStudioHistoryRoute: typeof ControlCenterAerospawnDesignStudioHistoryRoute
  ControlCenterAerospawnDesignStudioNewRoute: typeof ControlCenterAerospawnDesignStudioNewRoute
  ControlCenterAerospawnDesignStudioReportRoute: typeof ControlCenterAerospawnDesignStudioReportRoute
  ControlCenterAerospawnDesignStudioRequirementsRoute: typeof ControlCenterAerospawnDesignStudioRequirementsRoute
  ControlCenterAerospawnDesignStudioSimulationRoute: typeof ControlCenterAerospawnDesignStudioSimulationRoute
  ControlCenterAerospawnDesignStudioIndexRoute: typeof ControlCenterAerospawnDesignStudioIndexRoute
}

const ControlCenterAerospawnDesignStudioRouteChildren: ControlCenterAerospawnDesignStudioRouteChildren =
  {
    ControlCenterAerospawnDesignStudioAdvisorRoute:
      ControlCenterAerospawnDesignStudioAdvisorRoute,
    ControlCenterAerospawnDesignStudioComplianceRoute:
      ControlCenterAerospawnDesignStudioComplianceRoute,
    ControlCenterAerospawnDesignStudioComponentsRoute:
      ControlCenterAerospawnDesignStudioComponentsRoute,
    ControlCenterAerospawnDesignStudioDesignRoute:
      ControlCenterAerospawnDesignStudioDesignRoute,
    ControlCenterAerospawnDesignStudioHistoryRoute:
      ControlCenterAerospawnDesignStudioHistoryRoute,
    ControlCenterAerospawnDesignStudioNewRoute:
      ControlCenterAerospawnDesignStudioNewRoute,
    ControlCenterAerospawnDesignStudioReportRoute:
      ControlCenterAerospawnDesignStudioReportRoute,
    ControlCenterAerospawnDesignStudioRequirementsRoute:
      ControlCenterAerospawnDesignStudioRequirementsRoute,
    ControlCenterAerospawnDesignStudioSimulationRoute:
      ControlCenterAerospawnDesignStudioSimulationRoute,
    ControlCenterAerospawnDesignStudioIndexRoute:
      ControlCenterAerospawnDesignStudioIndexRoute,
  }

const ControlCenterAerospawnDesignStudioRouteWithChildren =
  ControlCenterAerospawnDesignStudioRoute._addFileChildren(
    ControlCenterAerospawnDesignStudioRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FieldRoute: FieldRoute,
  MissionHubRoute: MissionHubRouteWithChildren,
  PilotRoute: PilotRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ControlCenterAerospawnDesignStudioRoute:
    ControlCenterAerospawnDesignStudioRouteWithChildren,
  ControlCenterAgriskyRoute: ControlCenterAgriskyRoute,
  ControlCenterLoginRoute: ControlCenterLoginRoute,
  ControlCenterUsersRoute: ControlCenterUsersRoute,
  ControlCenterIndexRoute: ControlCenterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
