/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlCenterIndexRouteImport } from './routes/control-center.index'
import { Route as PilotLoginRouteImport } from './routes/pilot.login'
import { Route as ControlCenterLoginRouteImport } from './routes/control-center.login'
import { Route as ControlCenterAgriskyRouteImport } from './routes/control-center.agrisky'

const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterIndexRoute = ControlCenterIndexRouteImport.update({
  id: '/control-center/',
  path: '/control-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotLoginRoute = PilotLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PilotRoute,
} as any)
const ControlCenterLoginRoute = ControlCenterLoginRouteImport.update({
  id: '/control-center/login',
  path: '/control-center/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterAgriskyRoute = ControlCenterAgriskyRouteImport.update({
  id: '/control-center/agrisky',
  path: '/control-center/agrisky',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pilot': typeof PilotRouteWithChildren
  '/control-center/agrisky': typeof ControlCenterAgriskyRoute
  '/control-center/login': typeof ControlCenterLoginRoute
  '/pilot/login': typeof PilotLoginRoute
  '/control-center/': typeof ControlCenterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pilot': typeof PilotRouteWithChildren
  '/control-center/agrisky': typeof ControlCenterAgriskyRoute
  '/control-center/login': typeof ControlCenterLoginRoute
  '/pilot/login': typeof PilotLoginRoute
  '/control-center': typeof ControlCenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pilot': typeof PilotRouteWithChildren
  '/control-center/agrisky': typeof ControlCenterAgriskyRoute
  '/control-center/login': typeof ControlCenterLoginRoute
  '/pilot/login': typeof PilotLoginRoute
  '/control-center/': typeof ControlCenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pilot'
    | '/control-center/agrisky'
    | '/control-center/login'
    | '/pilot/login'
    | '/control-center/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pilot'
    | '/control-center/agrisky'
    | '/control-center/login'
    | '/pilot/login'
    | '/control-center'
  id:
    | '__root__'
    | '/'
    | '/pilot'
    | '/control-center/agrisky'
    | '/control-center/login'
    | '/pilot/login'
    | '/control-center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PilotRoute: typeof PilotRouteWithChildren
  ControlCenterAgriskyRoute: typeof ControlCenterAgriskyRoute
  ControlCenterLoginRoute: typeof ControlCenterLoginRoute
  ControlCenterIndexRoute: typeof ControlCenterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/': {
      id: '/control-center/'
      path: '/control-center'
      fullPath: '/control-center/'
      preLoaderRoute: typeof ControlCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/login': {
      id: '/pilot/login'
      path: '/login'
      fullPath: '/pilot/login'
      preLoaderRoute: typeof PilotLoginRouteImport
      parentRoute: typeof PilotRoute
    }
    '/control-center/login': {
      id: '/control-center/login'
      path: '/control-center/login'
      fullPath: '/control-center/login'
      preLoaderRoute: typeof ControlCenterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/agrisky': {
      id: '/control-center/agrisky'
      path: '/control-center/agrisky'
      fullPath: '/control-center/agrisky'
      preLoaderRoute: typeof ControlCenterAgriskyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PilotRouteChildren {
  PilotLoginRoute: typeof PilotLoginRoute
}

const PilotRouteChildren: PilotRouteChildren = {
  PilotLoginRoute: PilotLoginRoute,
}

const PilotRouteWithChildren = PilotRoute._addFileChildren(PilotRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PilotRoute: PilotRouteWithChildren,
  ControlCenterAgriskyRoute: ControlCenterAgriskyRoute,
  ControlCenterLoginRoute: ControlCenterLoginRoute,
  ControlCenterIndexRoute: ControlCenterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
